---

- name: "Ensure apache2 group exists"
  group:
    name: "{{ apache_group }}"
    state: present
  become: yes

- name: Check if changes need to be made
  user:
    name: "{{ apache_user }}"
    groups:
      - "{{ apache_group }}"
      - "{{ rtorrent_group }}"
    comment: "{{ apache_gecos }}"
    shell: "{{ apache_shell }}"
    home: "{{ apache_home }}"
    create_home: yes
    append: yes
  check_mode: yes
  register: changes_needed

- name: Stop service apache2, if changes needed
  service:
    name: apache2
    state: stopped
  become: yes
  when: changes_needed.changed
  notify: restart apache2

## Ensure www-data has access to torrent files in order to download from rutorrent
- name: "Apply desired state to user"
  user:
    name: "{{ apache_user }}"
    groups:
      - "{{ apache_group }}"
      - "{{ rtorrent_group }}"
    comment: "{{ apache_gecos }}"
    shell: "{{ apache_shell }}"
    home: "{{ apache_home }}"
    create_home: yes
    append: yes
  become: yes
  when: changes_needed.changed
