---
- name: "Ensure apache2 group exists"
  group:
    name: "{{apache['group']}}"
    state: present
  become: yes

- name: Check if changes need to be made
  user:
    name: "{{apache['user']}}"
    groups: 
      - "{{apache['group']}}"
      - "{{rtorrent_group}}" # applied from facts
    comment: "{{apache['gecos']}}"
    shell: "{{apache['shell']}}"
    home: "{{apache['home']}}"
    create_home: yes
    append: yes
  check_mode: yes
  register: changes_needed

- name: Stop service apache2, if changes needed
  service:
    name: apache2
    state: stopped
  become: yes
  when: changes_needed.changed
  notify: restart apache2

## Ensure www-data has access to torrent files in order to download from rutorrent
- name: "Apply desired state to user"
  user:
    name: "{{apache['user']}}"
    groups: 
      - "{{apache['group']}}"
      - "{{rtorrent_group}}" # applied from facts
    comment: "{{apache['gecos']}}"
    shell: "{{apache['shell']}}"
    home: "{{apache['home']}}"
    create_home: yes
    append: yes
  when: changes_needed.changed
  become: yes
