- name: Install r(u)torrent preqs
  package:
    name: "{{ item }}"
    state: present
  with_items:
     - apache2-utils
     - curl
     - ffmpeg
     - git
     - openssl
     - mc
     - mediainfo
     - libapache2-mod-php
     - php
     - php-cli
     - php-curl
     - rar
     - sox
     - tmux
     - unrar
     - unzip
     - zip
  become: yes
