---

## Enable Modules
- name: enable mod scgi
  command:
    cmd: a2enmod scgi
  become: yes
  notify: restart apache2

- name: enable mod proxy
  command:
    cmd: a2enmod proxy
  become: yes
  notify: restart apache2

- name: enable mod proxy_scgi
  command:
    cmd: a2enmod proxy_scgi
  become: yes
  notify: restart apache2

## Setup
- name: Copy sites config
  render:
    src: "templates/etc/apache2/sites-available/{{item}}.j2"
    dest: "/etc/apache2/sites-available/{{item}}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: '0444'
  with_items:
      - "001-rutorrent.conf"
  become: yes
  notify: restart apache2

- name: Copy sites config
  render:
    src: "templates/etc/apache2/{{item}}.j2"
    dest: "/etc/apache2/{{item}}"
    owner: "root"
    group: "root"
    mode: '0644'
  with_items:
      - ".htpasswd"
  become: yes
  notify: restart apache2

## Enable Sites
- name: disable default site
  command:
    cmd: a2dissite 000-default.conf
  become: yes
  notify: restart apache2

- name: enable rutorrent
  command:
    cmd: a2ensite 001-rutorrent.conf
  become: yes
  notify: restart apache2
