---
# requires: acl
- name: Clone rtorrent
  git:
    repo: "https://github.com/Novik/ruTorrent.git"
    dest: "{{ rutorrent_install_dir }}"
  become: yes
  become_user: "{{ apache_user }}"

- name: Manage permissions
  file:
    path: "{{ rutorrent_install_dir }}"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    recurse: yes
  become: yes
