---

- name: Render systemd unit
  template:
    src: "templates/etc/systemd/system/{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - rtorrent.service
  become: true
  notify: restart rtorrent

- name: Make sure a service unit is running
  systemd:
    name: rtorrent
    state: started
  become: yes
