---
- name: "Add the rtorrent group"
  group:
    name: "{{ rtorrent_group }}"
    state: present
  become: yes

- name: "Add the rtorrent user"
  user:
    name: "{{ rtorrent_user }}"
    groups: "{{ rtorrent_group }}"
    comment: "{{ rtorrent_gecos }}"
    shell: "{{ rtorrent_shell }}"
    home: "{{ rtorrent_home }}"
    create_home: yes
    append: yes
  check_mode: yes
  register: changes_needed

- name: Stop service rtorrent, if changes needed
  service:
    name: rorrent
    state: stopped
  become: yes
  when: changes_needed.changed
  notify: restart rtorrent

## Do not set shell to nologin when using the tmux service
- name: "Add the rtorrent user"
  user:
    name: "{{ rtorrent_user }}"
    groups: "{{ rtorrent_group }}"
    comment: "{{ rtorrent_gecos }}"
    shell: "{{ rtorrent_shell }}"
    home: "{{ rtorrent_home }}"
    create_home: yes
    append: yes
  become: yes
  when: changes_needed.changed
