---
- name: "Set facts"
  set_fact:
    rtorrent_user: "{{rtorrent['user']}}"
    rtorrent_group: "{{rtorrent['group']}}"
    rtorrent_home: "{{rtorrent['home']}}"

- name: "Add the rtorrent group"
  group:
    name: "{{rtorrent['group']}}"
    state: present
  become: yes

## Do not set shell to nologin when using the tmux service
- name: "Add the rtorrent user"
  user:
    name: "{{rtorrent['user']}}"
    groups: "{{rtorrent['group']}}"
    comment: "{{rtorrent['gecos']}}"
    shell: "{{rtorrent['shell']}}"
    home: "{{rtorrent['home']}}"
    create_home: yes
    append: yes
  become: yes
