---
rutorrent:
    install_dir: /var/www/rutorrent
    server_name: rutorrent.example.com
    server_admin: webmaster@localhost
htpasswd:
    username: widelyinsecure
    crypt: $apr1$OHg.Rpvw$J2m7kwwWCTn/m//45BXKV0
pki:
    private_key: /etc/ssl/private/apache-selfsigned.key
    public_key: /etc/ssl/certs/apache-selfsigned.crt
